FROM golang:1.18beta2
LABEL os=linux
LABEL arch=amd64

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=1
ENV PATH="/go/bin/${GOOS}_${GOARCH}:${PATH}"
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig

# install build & runtime dependencies
RUN apt update \
    && apt install -f -o Dpkg::Options::="--force-overwrite" -y --no-install-recommends \
        pkg-config \
        libwebkit2gtk-4.0-dev \
        libgtk-3-dev \
    && rm -rf /var/lib/apt/lists/*
