name: Linux AMD64 Docker Image

on:
  push:
    paths:
      - '**.linux-amd64'
      - '.github/workflows/docker-image.linux-amd64.yml'
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile.linux-amd64 --tag wailsapp/cc:linux-amd64
    - name: Push the latest Docker image
      run: docker push wailsapp/cc:linux-amd64
